"""empty message

Revision ID: 192653901d4e
Revises: 82352504251d
Create Date: 2020-06-21 17:06:29.078523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192653901d4e'
down_revision = '82352504251d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
